### PR TITLE
Guest Wifi get/set

### PR DESCRIPTION
**Pull request by hugoKs3**
New API methods to get the Guest Wifi status and to enable/disable it.

### CODE REVIEW

**Comment by hugoKs3** [comment]
@Cyr-ius, could you please review this PR?

**Comment by hugoKs3** [comment]
@epenet are you able to review/merge this PR ?

**Comment by epenet** [comment]
I don't have rights.
On top of that the lint fails...

**Comment by hugoKs3** [comment]
Yeah... I've seen the lint failing but don't understand why...

**Comment by Cyr-ius** [comment]
A carriage return was missing at the end of the file and the import sorting was incorrect.
I just merged your code and generated a new version

**Comment by hugoKs3** [comment]
Thank you @Cyr-ius !
I'm preparing another PR in your livebox component got HA ;)

**Comment by Cyr-ius** [comment]
Awesome. Unfortunately I no longer own Liveboxes. But if you have json extracted from the livebox, I would be interested because I could integrate Tox to do tests

**Pull request merged**
